#!/bin/bash

echo "Display configurator:"
echo

all_on=`xrandr | grep " connected" | cut -f1 -d" " | tr -s "\n" " " | sed -e 's/^ *//' -e 's/ *$//'`
all=`xrandr | grep "connected" | cut -f1 -d" " | tr -s "\n" " "`
all_on_num=`echo $all_on | wc -w`
all_num=`echo $all | wc -w`
default=`echo $all_on | cut -f1 -d" "`
both=` echo "$all_on" | tr -s " " "+"`

# reset to default only
#xrandr --output $default --auto
xrandr --auto

echo "$all_on_num devices connected:"
echo "$all_on" | tr -s " " "\n"
echo "Default is $default"
echo

if [[ $all_on_num -lt 2 ]]
then
    echo "Only default connected."
    i3-nagbar -m "Display config" -t warning -b "$default"  "xrandr"
else
    echo "More configurations possible:"
    echo
    bar="i3-nagbar -m \"Display config\" "
    bbar=" -b \"$both\"  \"xrandr "
    mbar=" -b \"$both - mirrored\" \"xrandr "
    lineall=""
    for dp in $all_on
    do
        echo "$dp only"
        bar=$bar" -b \"$dp only\" \"xrandr --output $dp --auto "
        bbar=$bbar" --output $dp --auto "
        mbar=$mbar" --output $dp --auto "
        for od in $all_on
        do
            if [[ "$dp" != "$od" ]]
            then
                bar=$bar" --output $od --off "
            fi
        done
        bar=$bar"\""
    done
    echo "$both"
    echo "$both - mirror"
    bbar=$bbar" --left-of $default\""
    mbar=$mbar" --same-as $default\""
    bar=$bar$bbar$mbar" -t warning"
    echo
    echo $bar
    eval $bar
fi
